### ISSUE TITLE
Polkadot.js/apps unable to retrieve block details

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1315]
## Describe the bug

- While using polkadot-js/apps web ui (connected locally), clicking a block number from within the explorer gives error: `Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicUnknown):: Unsupported unsigned extrinsic version 3` 

More details:
- I've determine that this error is caused when polkadot.js `api.rpc.chain.getBlock()` is called.  
- Here is error trace: 
```
2021-01-19 16:17:50        REGISTRY: Error: Unsupported unsigned extrinsic version 3
    at new GenericExtrinsicUnknown (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/extrinsic/ExtrinsicUnknown.js:26:11)
    at new Type (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/registry.js:300:16)
    at initType (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:68:12)
    at createType (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:83:10)
    at TypeRegistry.createType (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/registry.js:257:39)
    at Function._newFromValue (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/extrinsic/Extrinsic.js:202:21)
    at Function._decodeU8a (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/extrinsic/Extrinsic.js:233:29)
    at Function._decodeExtrinsic (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/extrinsic/Extrinsic.js:212:31)
    at new GenericExtrinsic (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/extrinsic/Extrinsic.js:188:38)
2021-01-19 16:17:50             VEC: Unable to decode on index 0 createType(ExtrinsicUnknown):: Unsupported unsigned extrinsic version 3
2021-01-19 16:17:50        REGISTRY: Error: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicUnknown):: Unsupported unsigned extrinsic version 3
    at Object.keys.reduce (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/codec/Struct.js:70:13)
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/codec/Struct.js:24:29)
    at decodeStruct (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/codec/Struct.js:111:10)
    at new Struct (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/codec/Struct.js:132:26)
    at new <anonymous> (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/codec/Struct.js:150:9)
    at new Type (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/registry.js:300:16)
    at initType (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:68:12)
    at RpcCore._formatOutput (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/rpc-core/index.js:398:41)
2021-01-19 16:17:50        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicUnknown):: Unsupported unsigned extrinsic version 3
(node:35046) UnhandledPromiseRejectionWarning: Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicUnknown):: Unsupported unsigned extrinsic version 3
    at createTypeUnsafe (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/types/create/createType.js:71:11)
    at RpcCore._formatOutput (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/rpc-core/index.js:398:41)
    at callWithRegistry (/home/emack/projects/polkadot-js/ejmTests/apiTestV8/node_modules/@polkadot/rpc-core/index.js:260:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



```
## Expected Behavior

- Clicking block number from within explorer should show details about that block.

## Current Behavior

- Clicking on block number from within explorer gives error.

## Possible Solution

- unknown

## To Reproduce

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by noot** [comment]
I wonder if this is related to the "gossamer" runtime, maybe try with kusama or polkadot runtimes?
