### ISSUE TITLE
Fix scale reflect.Value.IsNil on array Value panic while sync between nodes

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#1649]
## Describe the bug

- While 2 nodes are syncing then this panic appears in the node 01:
`panic: reflect: call of reflect.Value.IsNil on array Value`

## Current Behavior

- The syncing between nodes is not working properly

## To Reproduce
Steps to reproduce the behaviour:

1.  Run node 01: `./bin/gossamer --chain dev`
2. Run node 02: `./bin/gossamer --chain dev --key bob --port 7002 --bootnodes {node-01-addr} --basepath ./tmp`

## Log output

<details>
  <summary>Log Output</summary>
  
  ```
panic: reflect: call of reflect.Value.IsNil on array Value

goroutine 1074 [running]:
reflect.Value.IsNil(...)
	/usr/local/go/src/reflect/value.go:1086
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeCustom(0xc0058af730, 0x5726e00, 0xc0057d45a0, 0x4, 0xffffffffffffffff, 0x5726e01, 0xc0057d45a0)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode_ptr.go:82 +0x71d
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).Decode(0xc0058af730, 0x5726e00, 0xc0057d45a0, 0x1, 0x5726e00, 0xc0057d45a0, 0x191)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:97 +0x2d0
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeTuple(0xc0058af730, 0x56e0c40, 0xc0009b20e0, 0x5761bc0, 0xc0009b20e0, 0x199, 0x5f89372)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:590 +0x5fb
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeInterface(0xc0058af730, 0x56e0c40, 0xc0009b20e0, 0x5, 0xffffffffffffffff, 0x1, 0x8)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:351 +0x1fa
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).Decode(0xc0058af730, 0x56e0c40, 0xc0009b20e0, 0xc0025878c8, 0x581dce0, 0xc0025877d0, 0x30)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:102 +0x289
github.com/ChainSafe/gossamer/lib/grandpa.(*SignedPrecommit).Decode(0xc0009b20e0, 0x5c69160, 0xc0025877d0, 0x0, 0x0, 0x0)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/grandpa/types.go:213 +0x65
reflect.Value.call(0x56e0c40, 0xc0009b20e0, 0x213, 0x5845503, 0x4, 0xc0058afb10, 0x1, 0x1, 0x5c978c0, 0xc000f02de0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x56e0c40, 0xc0009b20e0, 0x213, 0xc0058afb10, 0x1, 0x1, 0xc0009b20e0, 0x213, 0xc000f02de0)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeCustom(0xc0058afeb0, 0x56e0c40, 0xc0009b20e0, 0x1, 0x56e0c40, 0x0, 0x196)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode_ptr.go:90 +0x335
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeSlice(0xc0058afeb0, 0x5657e60, 0xc0067d9110, 0xffffffffffffffff, 0x5f88897, 0x4400650000000047, 0x5f88897)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:452 +0x759
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).DecodeInterface(0xc0058afeb0, 0x5657e60, 0xc0067d9110, 0x0, 0x0, 0x5c694e0, 0xc0006f0b80)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:354 +0x4cb
github.com/ChainSafe/gossamer/lib/scale.(*Decoder).Decode(0xc0058afeb0, 0x5657e60, 0xc0067d9110, 0xc0067d9110, 0x5a, 0x0, 0x0)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/scale/decode.go:102 +0x289
github.com/ChainSafe/gossamer/lib/grandpa.(*Service).newCatchUpResponse(0xc000c7c5a0, 0xa, 0x0, 0xc0018fc2c0, 0x4, 0x4)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/grandpa/message.go:366 +0x25a
github.com/ChainSafe/gossamer/lib/grandpa.(*MessageHandler).handleCatchUpRequest(0xc00000e348, 0xc0006e6320, 0x18, 0xc001b489c0, 0x2)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/grandpa/message_handler.go:186 +0x171
github.com/ChainSafe/gossamer/lib/grandpa.(*MessageHandler).handleMessage(0xc00000e348, 0xc00669edb0, 0x26, 0x5c784f8, 0xc0006e6320, 0x6425940, 0x5f8677c, 0x5c, 0x5fd5031)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/grandpa/message_handler.go:75 +0x2a5
github.com/ChainSafe/gossamer/lib/grandpa.(*Service).handleNetworkMessage(0xc000c7c5a0, 0xc00669edb0, 0x26, 0x5c8b358, 0xc0067d8ff0, 0xc000e89740, 0x6, 0x6)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/lib/grandpa/network.go:157 +0xce
github.com/ChainSafe/gossamer/dot/network.(*Service).createNotificationsMessageHandler.func1(0x5c92ee8, 0xc006c3a960, 0xab75118, 0xc0067d8ff0, 0x6, 0x6)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/dot/network/notifications.go:191 +0x1130
github.com/ChainSafe/gossamer/dot/network.(*Service).readStream(0xc00027c540, 0x5c92ee8, 0xc006c3a960, 0xc000b7a0c0, 0xc000b7a100)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/dot/network/service.go:568 +0x6e7
github.com/ChainSafe/gossamer/dot/network.(*Service).RegisterNotificationsProtocol.func2(0x5c92ee8, 0xc006c3a960)
	/Users/eclesiojunior/go/src/github.com/ChainSafe/gossamer/dot/network/service.go:467 +0x151
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc0006f6b70, 0x15, 0xad54908, 0xc006c3a960, 0x1, 0x0)
	/Users/eclesiojunior/go/pkg/mod/github.com/libp2p/go-libp2p@v0.14.2/p2p/host/basic/basic_host.go:574 +0xa2
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/Users/eclesiojunior/go/pkg/mod/github.com/libp2p/go-libp2p@v0.14.2/p2p/host/basic/basic_host.go:421 +0x63a
  ```
</details> 
</br>

## Specification

- go version: 1.16.5
- gossamer version: development
- gossamer commit tag: n/a
- gossamer commit hash: n/a
- operating system: 
- additional links:

**Comment by noot** [comment]
closing this for now as the SCALE refactor should fix this
