### ISSUE TITLE
Sending on a closed channel in networks package

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2567]
## Describe the bug

- found this on one of the ci unit tests logs `panic: send on closed channel`
- Relevant logs might be this 
```
2022-05-25T13:43:24.3252053Z 2022-05-25T13:43:24Z INFO started network service with supported protocols /p2p/id/delta/1.0.0, /ipfs/id/1.0.0, /ipfs/id/push/1.0.0, /ipfs/ping/1.0.0, /gossamer/test/0/sync/2, /gossamer/test/0/light/2, /gossamer/test/0/block-announces/1, /gossamer/test/0/transactions/1	pkg=network
2022-05-25T13:43:24.3252553Z panic: send on closed channel
2022-05-25T13:43:24.3252708Z 
2022-05-25T13:43:24.3252815Z goroutine 10060 [running]:
2022-05-25T13:43:24.3253197Z github.com/ChainSafe/gossamer/dot/peerset.(*PeerSet).disconnect(0xc04b8d8200, 0x0, 0x0, {0xc04d65fe00, 0x1, 0x1?})
2022-05-25T13:43:24.3253660Z 	/home/runner/work/gossamer/gossamer/dot/peerset/peerset.go:693 +0x26f
2022-05-25T13:43:24.3254166Z github.com/ChainSafe/gossamer/dot/peerset.(*PeerSet).listenAction(0xc04b8d8200, {0x13b6200, 0xc04d62c380})
2022-05-25T13:43:24.3254611Z 	/home/runner/work/gossamer/gossamer/dot/peerset/peerset.go:752 +0x1b4
2022-05-25T13:43:24.3254996Z created by github.com/ChainSafe/gossamer/dot/peerset.(*PeerSet).start
2022-05-25T13:43:24.3255402Z 	/home/runner/work/gossamer/gossamer/dot/peerset/peerset.go:715 +0xea
2022-05-25T13:43:24.3255751Z FAIL	github.com/ChainSafe/gossamer/dot/network	77.287s
```

## Expected Behavior

- We should not be sending things on closed channels

## Current Behavior

-

## Possible Solution

-

## To Reproduce
- Running`./dot/network` unit tests should do it.

## Log output
- I have uploaded full CI logs here https://gist.github.com/kishansagathiya/b56af71482671c6c64aed8a1e9a60afa

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by kishansagathiya** [comment]
closed in https://github.com/ChainSafe/gossamer/pull/2573
