### ISSUE TITLE
Fix Flaky Test in `polkadotjs_test `

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#2754]
## Describe the bug

- https://github.com/ChainSafe/gossamer/runs/7844762885?check_suite_focus=true

```
start_polkadotjs_test.go:65: 
        	Error Trace:	/go/src/github.com/ChainSafe/gossamer/tests/polkadotjs_test/start_polkadotjs_test.go:65
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestStartGossamerAndPolkadotAPI
        	Messages:   	
        	            	
        	            	  Testing polkadot.js/api calls:
        	            	    api constants
        	            	2022-08-15 19:36:19        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32000: failed to get runtime instance: null
        	            	2022-08-15 19:36:19        API/INIT: Error: FATAL: Unable to initialize the API: -32000: failed to get runtime instance: null
        	            	    at ApiPromise._onProviderConnect2 (/go/src/github.com/ChainSafe/gossamer/tests/polkadotjs_test/node_modules/@polkadot/api/cjs/base/Init.js:431:19)
        	            	    at processTicksAndRejections (internal/process/task_queues.js:95:5)
        	            	2022-08-15 19:36:19        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: -32000: failed to get runtime instance: null
    start_polkadotjs_test.go:[60](https://github.com/ChainSafe/gossamer/runs/7844762885?check_suite_focus=true#step:3:61): Node alice-0 terminated
```

**Comment by timwu20** [comment]
@EclesioMeloJunior is this still flakey?

**Comment by EclesioMeloJunior** [comment]
@timwu20 yes, they still flaky in our CI
