### ISSUE TITLE
allocator "size too large" error

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#866]
## Expected Behavior

- no panics or errors in ext_malloc

## Current Behavior

```
t=2020-05-18T18:59:08-0400 lvl=eror msg=[ext_malloc] Error:="size to large"
panic: size to large

goroutine 1078 [running]:
github.com/ChainSafe/gossamer/lib/runtime.ext_malloc(0x7f0bdc0092e0, 0xc02854d400, 0x10)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/runtime/imports.go:97 +0x247
github.com/ChainSafe/gossamer/lib/runtime._cgoexpwrap_efa99758ed51_ext_malloc(0x7f0bdc0092e0, 0x2854d400, 0x7f0b47ffdc40)
	_cgo_gotypes.go:210 +0x33
github.com/wasmerio/go-ext-wasm/wasmer._Cfunc_wasmer_instance_call(0x7f0bdc10bb00, 0x7f0bdc0071f0, 0xc00015e1e0, 0xc000000002, 0xc0057421d0, 0x1, 0xc000000000)
	_cgo_gotypes.go:798 +0x4d
github.com/wasmerio/go-ext-wasm/wasmer.cWasmerInstanceCall(...)
	/home/elizabeth/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.2-0.20200326095750-0a32be6068ec/wasmer/bridge.go:503
github.com/wasmerio/go-ext-wasm/wasmer.getExportsFromInstance.func2(0xc008b9f0e0, 0x2, 0x2, 0x1b, 0xc0000a29f8, 0xc008bb4101, 0x0)
	/home/elizabeth/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.2-0.20200326095750-0a32be6068ec/wasmer/instance.go:365 +0x1f5
github.com/ChainSafe/gossamer/lib/runtime.(*Runtime).Exec(0xc0002880a0, 0xeadbde, 0x1b, 0xc005b17a28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/runtime/runtime.go:147 +0x27c
github.com/ChainSafe/gossamer/lib/runtime.(*Runtime).FinalizeBlock(0xc0002880a0, 0xeb0183, 0x1d, 0x5)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/runtime/helpers.go:135 +0x5c
github.com/ChainSafe/gossamer/lib/babe.(*Session).buildBlock(0xc0083c5c70, 0xc008a53a40, 0x5ec3133c, 0x3e8, 0x7, 0x2, 0x2, 0x0)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/babe/build.go:85 +0x635
github.com/ChainSafe/gossamer/lib/babe.(*Session).handleSlot(0xc0083c5c70, 0x7)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/babe/babe.go:317 +0x1ab
github.com/ChainSafe/gossamer/lib/babe.(*Session).invokeBlockAuthoring(0xc0083c5c70)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/babe/babe.go:282 +0x25d
created by github.com/ChainSafe/gossamer/lib/babe.(*Session).Start
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/lib/babe/babe.go:159 +0x274
```

## Possible Solution

- this can be fixed easily by removing the panics in ext_malloc. however, we should figure out why a "size too large" error is being returned in the first place, since if we don't panic and return some integer, it can cause other runtime memory problems down the line

## Steps to Reproduce

1. `make it-stress`
2. panics every so often, more likely with greater `NETWORK_SIZE`

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
this is probably related to #903

**Comment by noot** [comment]
closing in favour of #903
